version: "1"
services:
  app:
    build: .
    environment:
      - tmdbkey=${tmdbkey}
    command: python -u app.py
    ports:
      - "5000:5001"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: movies_mongodb
    ports:
      - 27017:27017